#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Vision) iris_vision
#
# @type Quadrotor Wide
#

sh /etc/init.d-posix/10016_iris

if [ $AUTOCNF = yes ]
then
	param set SYS_MC_EST_GROUP 2
	# EKF2: Vision position and heading
	param set EKF2_AID_MASK 321
	param set EKF2_EV_DELAY 5


	# LPE: Vision + baro
	# param set LPE_FUSION 132
	# AEQ: External heading set to use vision input
	# param set ATT_EXT_HDG_M 1
fi
