name: SITL Tests

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-simulation-bionic:2020-01-13
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Download MAVSDK
      run: wget https://github.com/mavlink/MAVSDK/releases/download/v0.24.0/mavsdk_0.24.0_ubuntu18.04_amd64.deb
    - name: Install MAVSDK
      run: dpkg -i mavsdk_0.24.0_ubuntu18.04_amd64.deb
    - name: Build PX4 in SITL integration test mode
      run: DONT_RUN=1 make px4_sitl gazebo mavsdk_tests
    - name: Run multicopter simulation test
      run:  test/mavsdk_tests/mavsdk_test_runner.py --model iris --speed-factor 20 --iterations 1 --fail-early
    - name: Run multicopter with optical flow simulation test
      run:  test/mavsdk_tests/mavsdk_test_runner.py --model iris_opt_flow --speed-factor 1 --iterations 1 --fail-early
